source "https://rubygems.org"

gem "metanorma-cli", git: "https://github.com/metanorma/metanorma-cli", branch: "main"
gem "debug"
gem "sassc-embedded"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "main"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma", git: "https://github.com/metanorma/metanorma", branch: "main"
gem "metanorma-taste", git: "https://github.com/metanorma/metanorma-taste", branch: "main"
gem "metanorma-utils", git: "https://github.com/metanorma/metanorma-utils", branch: "main"
gem "suma", git: "https://github.com/metanorma/suma", branch: "main"
gem "relaton", "= 3.0.0.pre.alpha.11"
gem "relaton-render", "= 3.0.0.pre.alpha.19"
gem "relaton-bib", "2.2.0.pre.alpha.1"
gem "pubid", github: "pubid/pubid", branch: "main"
gem "moxml", github: "lutaml/moxml", branch: "main"
gem "leptris", "1.9.331.0"
gem "lutaml-model", "= 0.8.97"
gem "metanorma-plugin-lutaml", github: "metanorma/metanorma-plugin-lutaml", branch: "main"
gem "metanorma-ogc", github: "metanorma/metanorma-ogc", branch: "main"
gem "metanorma-itu", github: "metanorma/metanorma-itu", branch: "main"
gem "metanorma-ieee", github: "metanorma/metanorma-ieee", branch: "main"
gem "metanorma-iho", github: "metanorma/metanorma-iho", branch: "main"
gem "metanorma-bipm", github: "metanorma/metanorma-bipm", branch: "main"
gem "metanorma-iec", github: "metanorma/metanorma-iec", branch: "main"
gem "metanorma-jis", github: "metanorma/metanorma-jis", branch: "main"
